// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5h5Av7HkvM5lqKVuWDXp7lFVCARl75FQ',
    appId: '1:412142553346:android:b16696ebc4f2b3eff75a1b',
    messagingSenderId: '412142553346',
    projectId: 'chat-app-v01-34ea5',
    databaseURL: 'https://chat-app-v01-34ea5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-v01-34ea5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Iq5urx56_zoSyV5LcztYsG4C5j7Pu3I',
    appId: '1:412142553346:ios:6bb36ac52c41e152f75a1b',
    messagingSenderId: '412142553346',
    projectId: 'chat-app-v01-34ea5',
    databaseURL: 'https://chat-app-v01-34ea5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-v01-34ea5.firebasestorage.app',
    iosBundleId: 'com.example.chatAppV01',
  );
}